### ISSUE TITLE
Make abbreviations for positions

### ISSUE THREAD

**Issue by Zackhardtoname** [Zackhardtoname/internships#19]
SDE = software engineering
FE: frontend
BE: backend
...

**Comment by MercureTony** [comment]
How can I contribute to this issue?

**Comment by Zackhardtoname** [comment]
Thank you! I think it'd be best to work on this issue after pull request #17 is resolved (author is @SteveErickson-J but I think he might be busy right now) since the position names would be standardized. If you want, could you 

- resolve the merge conflict
- shorten the position names into abbreviations as you see fit (Excel could be helpful in replacing texts)
- add some sort of dictionary in the repo_info.md file

Thank you!

**Comment by MercureTony** [comment]
How do you want the dictionary to refer to? Is it for the abbreviations? 

Also, I was wondering if it was a good idea to abbreviate it? Should we standardize it?

**Comment by Zackhardtoname** [comment]
Yes. Sorry if I wasn't clear. The dictionary is for the abbreviations as a standardized reference.
I think it would be nice since the table would then have less text and people can read/process it more easily while saving more space on the [website](https://zacklight.com/internships/). What do you think? It could be a bad idea since I only see companies abbreviation software engineering into SDE.

**Comment by Zackhardtoname** [comment]
Done See PR #25
