### ISSUE TITLE
question

### ISSUE THREAD

**Issue by atherdon** [Zackhardtoname/internships#28]
I'm running an internship program at my company - is there any qualification process for companies?
Nice project, btw

**Comment by Zackhardtoname** [comment]
Not really. I think if it is an unpaid internship or has any special circumstances, please add the information to the Notes column. :)

Any other questions?

**Comment by atherdon** [comment]
great - thank you! 
No questions at this moment. will add a PR soon - thanks for this opportunity!

**Comment by atherdon** [comment]
:(

**Comment by Zackhardtoname** [comment]
What is that for...

**Comment by atherdon** [comment]
i'm not finished and you close an issue. btw, i'm adding your repository to my article at hackernoon.
will share a link with you when it will be published

**Comment by atherdon** [comment]
check this PR: #32

**Comment by LGA112660** [comment]
Atherdon, 
I'm not sure which city your company resides in But,  I'm Interested in your Internship program. I have a eMPA and certifications in Python3,  SQL,  C++ . May I send you my resume? I'm practicing daily working incrementally on more courses.

**Comment by atherdon** [comment]
@LGA112660 we working remotely, our collaborators spread worldwide :) use my email: arthur.tkachenko.netweight@gmail.com

**Comment by LGA112660** [comment]
Great,
I will send my resume as soon as possible. Thanks You!

**Comment by atherdon** [comment]
take as much time as you need. we don't have rush here

>

**Comment by Zackhardtoname** [comment]
@atherdon 
Hi Arthur,

Sorry! I closed your issue since it seemed like your issue was resolved, and you said you had no questions left. Maybe the next time I could have asked more explicitly. Thank you!

Zack

**Comment by atherdon** [comment]
no problem at all Zack, you doing a great thing with this project! I like
it. Maybe you have plans how to move it forward?

>
